// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FilteringSorting.proto

package com.dbmapp.grpc;

public final class FilteringSortingServiceImpl {
  private FilteringSortingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FilterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FilterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Database schema
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    java.lang.String getSchemaName();
    /**
     * <pre>
     * Database schema
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSchemaNameBytes();

    /**
     * <pre>
     * Table to query
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    java.lang.String getTableName();
    /**
     * <pre>
     * Table to query
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <pre>
     * Column to apply filter
     * </pre>
     *
     * <code>string column = 3;</code>
     */
    java.lang.String getColumn();
    /**
     * <pre>
     * Column to apply filter
     * </pre>
     *
     * <code>string column = 3;</code>
     */
    com.google.protobuf.ByteString
        getColumnBytes();

    /**
     * <pre>
     * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
     * </pre>
     *
     * <code>string operation = 4;</code>
     */
    java.lang.String getOperation();
    /**
     * <pre>
     * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
     * </pre>
     *
     * <code>string operation = 4;</code>
     */
    com.google.protobuf.ByteString
        getOperationBytes();

    /**
     * <pre>
     * Value to compare
     * </pre>
     *
     * <code>string value = 5;</code>
     */
    java.lang.String getValue();
    /**
     * <pre>
     * Value to compare
     * </pre>
     *
     * <code>string value = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <pre>
     * Optional: ASC or DESC
     * </pre>
     *
     * <code>string sort_order = 6;</code>
     */
    java.lang.String getSortOrder();
    /**
     * <pre>
     * Optional: ASC or DESC
     * </pre>
     *
     * <code>string sort_order = 6;</code>
     */
    com.google.protobuf.ByteString
        getSortOrderBytes();
  }
  /**
   * <pre>
   * Message: FilterRequest
   * -----------------------------------------------
   * Sent by the client to define filtering and sorting criteria.
   * </pre>
   *
   * Protobuf type {@code FilterRequest}
   */
  public  static final class FilterRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FilterRequest)
      FilterRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FilterRequest.newBuilder() to construct.
    private FilterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FilterRequest() {
      schemaName_ = "";
      tableName_ = "";
      column_ = "";
      operation_ = "";
      value_ = "";
      sortOrder_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FilterRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              schemaName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              column_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              operation_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              sortOrder_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest.class, com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest.Builder.class);
    }

    public static final int SCHEMA_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object schemaName_;
    /**
     * <pre>
     * Database schema
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Database schema
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object tableName_;
    /**
     * <pre>
     * Table to query
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Table to query
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMN_FIELD_NUMBER = 3;
    private volatile java.lang.Object column_;
    /**
     * <pre>
     * Column to apply filter
     * </pre>
     *
     * <code>string column = 3;</code>
     */
    public java.lang.String getColumn() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        column_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Column to apply filter
     * </pre>
     *
     * <code>string column = 3;</code>
     */
    public com.google.protobuf.ByteString
        getColumnBytes() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        column_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATION_FIELD_NUMBER = 4;
    private volatile java.lang.Object operation_;
    /**
     * <pre>
     * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
     * </pre>
     *
     * <code>string operation = 4;</code>
     */
    public java.lang.String getOperation() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operation_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
     * </pre>
     *
     * <code>string operation = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOperationBytes() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private volatile java.lang.Object value_;
    /**
     * <pre>
     * Value to compare
     * </pre>
     *
     * <code>string value = 5;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Value to compare
     * </pre>
     *
     * <code>string value = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SORT_ORDER_FIELD_NUMBER = 6;
    private volatile java.lang.Object sortOrder_;
    /**
     * <pre>
     * Optional: ASC or DESC
     * </pre>
     *
     * <code>string sort_order = 6;</code>
     */
    public java.lang.String getSortOrder() {
      java.lang.Object ref = sortOrder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sortOrder_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional: ASC or DESC
     * </pre>
     *
     * <code>string sort_order = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSortOrderBytes() {
      java.lang.Object ref = sortOrder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sortOrder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSchemaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schemaName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableName_);
      }
      if (!getColumnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, column_);
      }
      if (!getOperationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, operation_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, value_);
      }
      if (!getSortOrderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sortOrder_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSchemaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schemaName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableName_);
      }
      if (!getColumnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, column_);
      }
      if (!getOperationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, operation_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, value_);
      }
      if (!getSortOrderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sortOrder_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest)) {
        return super.equals(obj);
      }
      com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest other = (com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest) obj;

      boolean result = true;
      result = result && getSchemaName()
          .equals(other.getSchemaName());
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && getColumn()
          .equals(other.getColumn());
      result = result && getOperation()
          .equals(other.getOperation());
      result = result && getValue()
          .equals(other.getValue());
      result = result && getSortOrder()
          .equals(other.getSortOrder());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaName().hashCode();
      hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (37 * hash) + COLUMN_FIELD_NUMBER;
      hash = (53 * hash) + getColumn().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getOperation().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + SORT_ORDER_FIELD_NUMBER;
      hash = (53 * hash) + getSortOrder().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: FilterRequest
     * -----------------------------------------------
     * Sent by the client to define filtering and sorting criteria.
     * </pre>
     *
     * Protobuf type {@code FilterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FilterRequest)
        com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilterRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest.class, com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest.Builder.class);
      }

      // Construct using com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schemaName_ = "";

        tableName_ = "";

        column_ = "";

        operation_ = "";

        value_ = "";

        sortOrder_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilterRequest_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest getDefaultInstanceForType() {
        return com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest build() {
        com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest buildPartial() {
        com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest result = new com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest(this);
        result.schemaName_ = schemaName_;
        result.tableName_ = tableName_;
        result.column_ = column_;
        result.operation_ = operation_;
        result.value_ = value_;
        result.sortOrder_ = sortOrder_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest) {
          return mergeFrom((com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest other) {
        if (other == com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest.getDefaultInstance()) return this;
        if (!other.getSchemaName().isEmpty()) {
          schemaName_ = other.schemaName_;
          onChanged();
        }
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        if (!other.getColumn().isEmpty()) {
          column_ = other.column_;
          onChanged();
        }
        if (!other.getOperation().isEmpty()) {
          operation_ = other.operation_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (!other.getSortOrder().isEmpty()) {
          sortOrder_ = other.sortOrder_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object schemaName_ = "";
      /**
       * <pre>
       * Database schema
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public java.lang.String getSchemaName() {
        java.lang.Object ref = schemaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schemaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Database schema
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaNameBytes() {
        java.lang.Object ref = schemaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Database schema
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schemaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Database schema
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder clearSchemaName() {
        
        schemaName_ = getDefaultInstance().getSchemaName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Database schema
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schemaName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tableName_ = "";
      /**
       * <pre>
       * Table to query
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Table to query
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Table to query
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Table to query
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Table to query
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object column_ = "";
      /**
       * <pre>
       * Column to apply filter
       * </pre>
       *
       * <code>string column = 3;</code>
       */
      public java.lang.String getColumn() {
        java.lang.Object ref = column_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          column_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Column to apply filter
       * </pre>
       *
       * <code>string column = 3;</code>
       */
      public com.google.protobuf.ByteString
          getColumnBytes() {
        java.lang.Object ref = column_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          column_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Column to apply filter
       * </pre>
       *
       * <code>string column = 3;</code>
       */
      public Builder setColumn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Column to apply filter
       * </pre>
       *
       * <code>string column = 3;</code>
       */
      public Builder clearColumn() {
        
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Column to apply filter
       * </pre>
       *
       * <code>string column = 3;</code>
       */
      public Builder setColumnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        column_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object operation_ = "";
      /**
       * <pre>
       * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
       * </pre>
       *
       * <code>string operation = 4;</code>
       */
      public java.lang.String getOperation() {
        java.lang.Object ref = operation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
       * </pre>
       *
       * <code>string operation = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOperationBytes() {
        java.lang.Object ref = operation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
       * </pre>
       *
       * <code>string operation = 4;</code>
       */
      public Builder setOperation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
       * </pre>
       *
       * <code>string operation = 4;</code>
       */
      public Builder clearOperation() {
        
        operation_ = getDefaultInstance().getOperation();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Filter operation (=, !=, &gt;, &lt;, &gt;=, &lt;=)
       * </pre>
       *
       * <code>string operation = 4;</code>
       */
      public Builder setOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <pre>
       * Value to compare
       * </pre>
       *
       * <code>string value = 5;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Value to compare
       * </pre>
       *
       * <code>string value = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Value to compare
       * </pre>
       *
       * <code>string value = 5;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Value to compare
       * </pre>
       *
       * <code>string value = 5;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Value to compare
       * </pre>
       *
       * <code>string value = 5;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sortOrder_ = "";
      /**
       * <pre>
       * Optional: ASC or DESC
       * </pre>
       *
       * <code>string sort_order = 6;</code>
       */
      public java.lang.String getSortOrder() {
        java.lang.Object ref = sortOrder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sortOrder_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional: ASC or DESC
       * </pre>
       *
       * <code>string sort_order = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSortOrderBytes() {
        java.lang.Object ref = sortOrder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sortOrder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional: ASC or DESC
       * </pre>
       *
       * <code>string sort_order = 6;</code>
       */
      public Builder setSortOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sortOrder_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional: ASC or DESC
       * </pre>
       *
       * <code>string sort_order = 6;</code>
       */
      public Builder clearSortOrder() {
        
        sortOrder_ = getDefaultInstance().getSortOrder();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional: ASC or DESC
       * </pre>
       *
       * <code>string sort_order = 6;</code>
       */
      public Builder setSortOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sortOrder_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FilterRequest)
    }

    // @@protoc_insertion_point(class_scope:FilterRequest)
    private static final com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest();
    }

    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilterRequest>
        PARSER = new com.google.protobuf.AbstractParser<FilterRequest>() {
      @java.lang.Override
      public FilterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FilterRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FilterRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilterRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.grpc.FilteringSortingServiceImpl.FilterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FilteredRowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FilteredRow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The entire row returned from the query
     * </pre>
     *
     * <code>repeated string values = 1;</code>
     */
    java.util.List<java.lang.String>
        getValuesList();
    /**
     * <pre>
     * The entire row returned from the query
     * </pre>
     *
     * <code>repeated string values = 1;</code>
     */
    int getValuesCount();
    /**
     * <pre>
     * The entire row returned from the query
     * </pre>
     *
     * <code>repeated string values = 1;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <pre>
     * The entire row returned from the query
     * </pre>
     *
     * <code>repeated string values = 1;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);
  }
  /**
   * <pre>
   * Message: FilteredRow
   * -----------------------------------------------
   * One row returned by the server that matched the filter.
   * </pre>
   *
   * Protobuf type {@code FilteredRow}
   */
  public  static final class FilteredRow extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FilteredRow)
      FilteredRowOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FilteredRow.newBuilder() to construct.
    private FilteredRow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FilteredRow() {
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FilteredRow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              values_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = values_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilteredRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilteredRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow.class, com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow.Builder.class);
    }

    public static final int VALUES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <pre>
     * The entire row returned from the query
     * </pre>
     *
     * <code>repeated string values = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValuesList() {
      return values_;
    }
    /**
     * <pre>
     * The entire row returned from the query
     * </pre>
     *
     * <code>repeated string values = 1;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <pre>
     * The entire row returned from the query
     * </pre>
     *
     * <code>repeated string values = 1;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <pre>
     * The entire row returned from the query
     * </pre>
     *
     * <code>repeated string values = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < values_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, values_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += computeStringSizeNoTag(values_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow)) {
        return super.equals(obj);
      }
      com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow other = (com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow) obj;

      boolean result = true;
      result = result && getValuesList()
          .equals(other.getValuesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: FilteredRow
     * -----------------------------------------------
     * One row returned by the server that matched the filter.
     * </pre>
     *
     * Protobuf type {@code FilteredRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FilteredRow)
        com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilteredRow_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilteredRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow.class, com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow.Builder.class);
      }

      // Construct using com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.grpc.FilteringSortingServiceImpl.internal_static_FilteredRow_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow getDefaultInstanceForType() {
        return com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow build() {
        com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow buildPartial() {
        com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow result = new com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = values_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.values_ = values_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow) {
          return mergeFrom((com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow other) {
        if (other == com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow.getDefaultInstance()) return this;
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValuesList() {
        return values_.getUnmodifiableView();
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The entire row returned from the query
       * </pre>
       *
       * <code>repeated string values = 1;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FilteredRow)
    }

    // @@protoc_insertion_point(class_scope:FilteredRow)
    private static final com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow();
    }

    public static com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilteredRow>
        PARSER = new com.google.protobuf.AbstractParser<FilteredRow>() {
      @java.lang.Override
      public FilteredRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FilteredRow(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FilteredRow> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilteredRow> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.grpc.FilteringSortingServiceImpl.FilteredRow getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilterRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilterRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilteredRow_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilteredRow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026FilteringSorting.proto\"~\n\rFilterReques" +
      "t\022\023\n\013schema_name\030\001 \001(\t\022\022\n\ntable_name\030\002 \001" +
      "(\t\022\016\n\006column\030\003 \001(\t\022\021\n\toperation\030\004 \001(\t\022\r\n" +
      "\005value\030\005 \001(\t\022\022\n\nsort_order\030\006 \001(\t\"\035\n\013Filt" +
      "eredRow\022\016\n\006values\030\001 \003(\t2I\n\020FilteringSort" +
      "ing\0225\n\021LiveFilterAndSort\022\016.FilterRequest" +
      "\032\014.FilteredRow(\0010\001B.\n\017com.dbmapp.grpcB\033F" +
      "ilteringSortingServiceImplb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilterRequest_descriptor,
        new java.lang.String[] { "SchemaName", "TableName", "Column", "Operation", "Value", "SortOrder", });
    internal_static_FilteredRow_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FilteredRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilteredRow_descriptor,
        new java.lang.String[] { "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
