// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableManagement.proto

package com.dbmapp.grpc;

public interface RowDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablemanagement.RowData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string values = 1;</code>
   */
  java.util.List<java.lang.String>
      getValuesList();
  /**
   * <code>repeated string values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated string values = 1;</code>
   */
  java.lang.String getValues(int index);
  /**
   * <code>repeated string values = 1;</code>
   */
  com.google.protobuf.ByteString
      getValuesBytes(int index);
}
