// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableManagement.proto

package com.dbmapp.grpc;

public interface SchemaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablemanagement.SchemaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string schemaName = 1;</code>
   */
  java.lang.String getSchemaName();
  /**
   * <code>string schemaName = 1;</code>
   */
  com.google.protobuf.ByteString
      getSchemaNameBytes();
}
