// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableManagement.proto

package com.dbmapp.grpc;

/**
 * <pre>
 * Response containing table data (column names and rows)
 * </pre>
 *
 * Protobuf type {@code tablemanagement.TableDataResponse}
 */
public  final class TableDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tablemanagement.TableDataResponse)
    TableDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TableDataResponse.newBuilder() to construct.
  private TableDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TableDataResponse() {
    columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    rows_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TableDataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              columnNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            columnNames_.add(s);
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              rows_ = new java.util.ArrayList<com.dbmapp.grpc.RowData>();
              mutable_bitField0_ |= 0x00000002;
            }
            rows_.add(
                input.readMessage(com.dbmapp.grpc.RowData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        columnNames_ = columnNames_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        rows_ = java.util.Collections.unmodifiableList(rows_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableDataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dbmapp.grpc.TableDataResponse.class, com.dbmapp.grpc.TableDataResponse.Builder.class);
  }

  public static final int COLUMNNAMES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList columnNames_;
  /**
   * <code>repeated string columnNames = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getColumnNamesList() {
    return columnNames_;
  }
  /**
   * <code>repeated string columnNames = 1;</code>
   */
  public int getColumnNamesCount() {
    return columnNames_.size();
  }
  /**
   * <code>repeated string columnNames = 1;</code>
   */
  public java.lang.String getColumnNames(int index) {
    return columnNames_.get(index);
  }
  /**
   * <code>repeated string columnNames = 1;</code>
   */
  public com.google.protobuf.ByteString
      getColumnNamesBytes(int index) {
    return columnNames_.getByteString(index);
  }

  public static final int ROWS_FIELD_NUMBER = 2;
  private java.util.List<com.dbmapp.grpc.RowData> rows_;
  /**
   * <code>repeated .tablemanagement.RowData rows = 2;</code>
   */
  public java.util.List<com.dbmapp.grpc.RowData> getRowsList() {
    return rows_;
  }
  /**
   * <code>repeated .tablemanagement.RowData rows = 2;</code>
   */
  public java.util.List<? extends com.dbmapp.grpc.RowDataOrBuilder> 
      getRowsOrBuilderList() {
    return rows_;
  }
  /**
   * <code>repeated .tablemanagement.RowData rows = 2;</code>
   */
  public int getRowsCount() {
    return rows_.size();
  }
  /**
   * <code>repeated .tablemanagement.RowData rows = 2;</code>
   */
  public com.dbmapp.grpc.RowData getRows(int index) {
    return rows_.get(index);
  }
  /**
   * <code>repeated .tablemanagement.RowData rows = 2;</code>
   */
  public com.dbmapp.grpc.RowDataOrBuilder getRowsOrBuilder(
      int index) {
    return rows_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < columnNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, columnNames_.getRaw(i));
    }
    for (int i = 0; i < rows_.size(); i++) {
      output.writeMessage(2, rows_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < columnNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(columnNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getColumnNamesList().size();
    }
    for (int i = 0; i < rows_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, rows_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dbmapp.grpc.TableDataResponse)) {
      return super.equals(obj);
    }
    com.dbmapp.grpc.TableDataResponse other = (com.dbmapp.grpc.TableDataResponse) obj;

    boolean result = true;
    result = result && getColumnNamesList()
        .equals(other.getColumnNamesList());
    result = result && getRowsList()
        .equals(other.getRowsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getColumnNamesCount() > 0) {
      hash = (37 * hash) + COLUMNNAMES_FIELD_NUMBER;
      hash = (53 * hash) + getColumnNamesList().hashCode();
    }
    if (getRowsCount() > 0) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRowsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dbmapp.grpc.TableDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dbmapp.grpc.TableDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dbmapp.grpc.TableDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dbmapp.grpc.TableDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response containing table data (column names and rows)
   * </pre>
   *
   * Protobuf type {@code tablemanagement.TableDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tablemanagement.TableDataResponse)
      com.dbmapp.grpc.TableDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.grpc.TableDataResponse.class, com.dbmapp.grpc.TableDataResponse.Builder.class);
    }

    // Construct using com.dbmapp.grpc.TableDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRowsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableDataResponse_descriptor;
    }

    @java.lang.Override
    public com.dbmapp.grpc.TableDataResponse getDefaultInstanceForType() {
      return com.dbmapp.grpc.TableDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.dbmapp.grpc.TableDataResponse build() {
      com.dbmapp.grpc.TableDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dbmapp.grpc.TableDataResponse buildPartial() {
      com.dbmapp.grpc.TableDataResponse result = new com.dbmapp.grpc.TableDataResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        columnNames_ = columnNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.columnNames_ = columnNames_;
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rows_ = rows_;
      } else {
        result.rows_ = rowsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dbmapp.grpc.TableDataResponse) {
        return mergeFrom((com.dbmapp.grpc.TableDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dbmapp.grpc.TableDataResponse other) {
      if (other == com.dbmapp.grpc.TableDataResponse.getDefaultInstance()) return this;
      if (!other.columnNames_.isEmpty()) {
        if (columnNames_.isEmpty()) {
          columnNames_ = other.columnNames_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureColumnNamesIsMutable();
          columnNames_.addAll(other.columnNames_);
        }
        onChanged();
      }
      if (rowsBuilder_ == null) {
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
      } else {
        if (!other.rows_.isEmpty()) {
          if (rowsBuilder_.isEmpty()) {
            rowsBuilder_.dispose();
            rowsBuilder_ = null;
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
            rowsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRowsFieldBuilder() : null;
          } else {
            rowsBuilder_.addAllMessages(other.rows_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dbmapp.grpc.TableDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dbmapp.grpc.TableDataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureColumnNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        columnNames_ = new com.google.protobuf.LazyStringArrayList(columnNames_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getColumnNamesList() {
      return columnNames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public int getColumnNamesCount() {
      return columnNames_.size();
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public java.lang.String getColumnNames(int index) {
      return columnNames_.get(index);
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColumnNamesBytes(int index) {
      return columnNames_.getByteString(index);
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public Builder setColumnNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnNamesIsMutable();
      columnNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public Builder addColumnNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnNamesIsMutable();
      columnNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public Builder addAllColumnNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureColumnNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, columnNames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public Builder clearColumnNames() {
      columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columnNames = 1;</code>
     */
    public Builder addColumnNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureColumnNamesIsMutable();
      columnNames_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<com.dbmapp.grpc.RowData> rows_ =
      java.util.Collections.emptyList();
    private void ensureRowsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        rows_ = new java.util.ArrayList<com.dbmapp.grpc.RowData>(rows_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dbmapp.grpc.RowData, com.dbmapp.grpc.RowData.Builder, com.dbmapp.grpc.RowDataOrBuilder> rowsBuilder_;

    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public java.util.List<com.dbmapp.grpc.RowData> getRowsList() {
      if (rowsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rows_);
      } else {
        return rowsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public int getRowsCount() {
      if (rowsBuilder_ == null) {
        return rows_.size();
      } else {
        return rowsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public com.dbmapp.grpc.RowData getRows(int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);
      } else {
        return rowsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder setRows(
        int index, com.dbmapp.grpc.RowData value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder setRows(
        int index, com.dbmapp.grpc.RowData.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder addRows(com.dbmapp.grpc.RowData value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder addRows(
        int index, com.dbmapp.grpc.RowData value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(index, value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder addRows(
        com.dbmapp.grpc.RowData.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder addRows(
        int index, com.dbmapp.grpc.RowData.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder addAllRows(
        java.lang.Iterable<? extends com.dbmapp.grpc.RowData> values) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
      } else {
        rowsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder clearRows() {
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public Builder removeRows(int index) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.remove(index);
        onChanged();
      } else {
        rowsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public com.dbmapp.grpc.RowData.Builder getRowsBuilder(
        int index) {
      return getRowsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public com.dbmapp.grpc.RowDataOrBuilder getRowsOrBuilder(
        int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);  } else {
        return rowsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public java.util.List<? extends com.dbmapp.grpc.RowDataOrBuilder> 
         getRowsOrBuilderList() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rows_);
      }
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public com.dbmapp.grpc.RowData.Builder addRowsBuilder() {
      return getRowsFieldBuilder().addBuilder(
          com.dbmapp.grpc.RowData.getDefaultInstance());
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public com.dbmapp.grpc.RowData.Builder addRowsBuilder(
        int index) {
      return getRowsFieldBuilder().addBuilder(
          index, com.dbmapp.grpc.RowData.getDefaultInstance());
    }
    /**
     * <code>repeated .tablemanagement.RowData rows = 2;</code>
     */
    public java.util.List<com.dbmapp.grpc.RowData.Builder> 
         getRowsBuilderList() {
      return getRowsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dbmapp.grpc.RowData, com.dbmapp.grpc.RowData.Builder, com.dbmapp.grpc.RowDataOrBuilder> 
        getRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dbmapp.grpc.RowData, com.dbmapp.grpc.RowData.Builder, com.dbmapp.grpc.RowDataOrBuilder>(
                rows_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tablemanagement.TableDataResponse)
  }

  // @@protoc_insertion_point(class_scope:tablemanagement.TableDataResponse)
  private static final com.dbmapp.grpc.TableDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dbmapp.grpc.TableDataResponse();
  }

  public static com.dbmapp.grpc.TableDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TableDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<TableDataResponse>() {
    @java.lang.Override
    public TableDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TableDataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TableDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TableDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dbmapp.grpc.TableDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

