// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableManagement.proto

package com.dbmapp.grpc;

public final class TableManagementServiceImpl {
  private TableManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablemanagement_SchemaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablemanagement_SchemaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablemanagement_TableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablemanagement_TableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablemanagement_TableListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablemanagement_TableListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablemanagement_TableDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablemanagement_TableDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablemanagement_RowData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablemanagement_RowData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablemanagement_ConfirmationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablemanagement_ConfirmationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025TableManagement.proto\022\017tablemanagement" +
      "\"#\n\rSchemaRequest\022\022\n\nschemaName\030\001 \001(\t\"G\n" +
      "\014TableRequest\022\022\n\nschemaName\030\001 \001(\t\022\021\n\ttab" +
      "leName\030\002 \001(\t\022\020\n\010rowLimit\030\003 \001(\005\"#\n\021TableL" +
      "istResponse\022\016\n\006tables\030\001 \003(\t\"P\n\021TableData" +
      "Response\022\023\n\013columnNames\030\001 \003(\t\022&\n\004rows\030\002 " +
      "\003(\0132\030.tablemanagement.RowData\"\031\n\007RowData" +
      "\022\016\n\006values\030\001 \003(\t\"2\n\023ConfirmationMessage\022" +
      "\n\n\002ok\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\210\002\n\017TableMa" +
      "nagement\022O\n\tGetTables\022\036.tablemanagement." +
      "SchemaRequest\032\".tablemanagement.TableLis" +
      "tResponse\022R\n\rViewTableData\022\035.tablemanage" +
      "ment.TableRequest\032\".tablemanagement.Tabl" +
      "eDataResponse\022P\n\tDropTable\022\035.tablemanage" +
      "ment.TableRequest\032$.tablemanagement.Conf" +
      "irmationMessageB/\n\017com.dbmapp.grpcB\032Tabl" +
      "eManagementServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tablemanagement_SchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tablemanagement_SchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablemanagement_SchemaRequest_descriptor,
        new java.lang.String[] { "SchemaName", });
    internal_static_tablemanagement_TableRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tablemanagement_TableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablemanagement_TableRequest_descriptor,
        new java.lang.String[] { "SchemaName", "TableName", "RowLimit", });
    internal_static_tablemanagement_TableListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tablemanagement_TableListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablemanagement_TableListResponse_descriptor,
        new java.lang.String[] { "Tables", });
    internal_static_tablemanagement_TableDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tablemanagement_TableDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablemanagement_TableDataResponse_descriptor,
        new java.lang.String[] { "ColumnNames", "Rows", });
    internal_static_tablemanagement_RowData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tablemanagement_RowData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablemanagement_RowData_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_tablemanagement_ConfirmationMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tablemanagement_ConfirmationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablemanagement_ConfirmationMessage_descriptor,
        new java.lang.String[] { "Ok", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
