// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableManagement.proto

package com.dbmapp.grpc;

/**
 * <pre>
 * Response containing list of tables
 * </pre>
 *
 * Protobuf type {@code tablemanagement.TableListResponse}
 */
public  final class TableListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tablemanagement.TableListResponse)
    TableListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TableListResponse.newBuilder() to construct.
  private TableListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TableListResponse() {
    tables_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TableListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              tables_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            tables_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        tables_ = tables_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dbmapp.grpc.TableListResponse.class, com.dbmapp.grpc.TableListResponse.Builder.class);
  }

  public static final int TABLES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList tables_;
  /**
   * <code>repeated string tables = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getTablesList() {
    return tables_;
  }
  /**
   * <code>repeated string tables = 1;</code>
   */
  public int getTablesCount() {
    return tables_.size();
  }
  /**
   * <code>repeated string tables = 1;</code>
   */
  public java.lang.String getTables(int index) {
    return tables_.get(index);
  }
  /**
   * <code>repeated string tables = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTablesBytes(int index) {
    return tables_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tables_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tables_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < tables_.size(); i++) {
        dataSize += computeStringSizeNoTag(tables_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTablesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dbmapp.grpc.TableListResponse)) {
      return super.equals(obj);
    }
    com.dbmapp.grpc.TableListResponse other = (com.dbmapp.grpc.TableListResponse) obj;

    boolean result = true;
    result = result && getTablesList()
        .equals(other.getTablesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTablesCount() > 0) {
      hash = (37 * hash) + TABLES_FIELD_NUMBER;
      hash = (53 * hash) + getTablesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dbmapp.grpc.TableListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dbmapp.grpc.TableListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dbmapp.grpc.TableListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dbmapp.grpc.TableListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response containing list of tables
   * </pre>
   *
   * Protobuf type {@code tablemanagement.TableListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tablemanagement.TableListResponse)
      com.dbmapp.grpc.TableListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.grpc.TableListResponse.class, com.dbmapp.grpc.TableListResponse.Builder.class);
    }

    // Construct using com.dbmapp.grpc.TableListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tables_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dbmapp.grpc.TableManagementServiceImpl.internal_static_tablemanagement_TableListResponse_descriptor;
    }

    @java.lang.Override
    public com.dbmapp.grpc.TableListResponse getDefaultInstanceForType() {
      return com.dbmapp.grpc.TableListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.dbmapp.grpc.TableListResponse build() {
      com.dbmapp.grpc.TableListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dbmapp.grpc.TableListResponse buildPartial() {
      com.dbmapp.grpc.TableListResponse result = new com.dbmapp.grpc.TableListResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        tables_ = tables_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tables_ = tables_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dbmapp.grpc.TableListResponse) {
        return mergeFrom((com.dbmapp.grpc.TableListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dbmapp.grpc.TableListResponse other) {
      if (other == com.dbmapp.grpc.TableListResponse.getDefaultInstance()) return this;
      if (!other.tables_.isEmpty()) {
        if (tables_.isEmpty()) {
          tables_ = other.tables_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTablesIsMutable();
          tables_.addAll(other.tables_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dbmapp.grpc.TableListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dbmapp.grpc.TableListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList tables_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTablesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        tables_ = new com.google.protobuf.LazyStringArrayList(tables_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTablesList() {
      return tables_.getUnmodifiableView();
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public int getTablesCount() {
      return tables_.size();
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public java.lang.String getTables(int index) {
      return tables_.get(index);
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTablesBytes(int index) {
      return tables_.getByteString(index);
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public Builder setTables(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTablesIsMutable();
      tables_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public Builder addTables(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTablesIsMutable();
      tables_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public Builder addAllTables(
        java.lang.Iterable<java.lang.String> values) {
      ensureTablesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tables_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public Builder clearTables() {
      tables_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tables = 1;</code>
     */
    public Builder addTablesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTablesIsMutable();
      tables_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tablemanagement.TableListResponse)
  }

  // @@protoc_insertion_point(class_scope:tablemanagement.TableListResponse)
  private static final com.dbmapp.grpc.TableListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dbmapp.grpc.TableListResponse();
  }

  public static com.dbmapp.grpc.TableListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TableListResponse>
      PARSER = new com.google.protobuf.AbstractParser<TableListResponse>() {
    @java.lang.Override
    public TableListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TableListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TableListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TableListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dbmapp.grpc.TableListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

