// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableManagement.proto

package com.dbmapp.grpc;

public interface TableListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablemanagement.TableListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string tables = 1;</code>
   */
  java.util.List<java.lang.String>
      getTablesList();
  /**
   * <code>repeated string tables = 1;</code>
   */
  int getTablesCount();
  /**
   * <code>repeated string tables = 1;</code>
   */
  java.lang.String getTables(int index);
  /**
   * <code>repeated string tables = 1;</code>
   */
  com.google.protobuf.ByteString
      getTablesBytes(int index);
}
