// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableManagement.proto

package com.dbmapp.grpc;

public interface TableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablemanagement.TableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string schemaName = 1;</code>
   */
  java.lang.String getSchemaName();
  /**
   * <code>string schemaName = 1;</code>
   */
  com.google.protobuf.ByteString
      getSchemaNameBytes();

  /**
   * <code>string tableName = 2;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string tableName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <pre>
   * Number of rows to retrieve
   * </pre>
   *
   * <code>int32 rowLimit = 3;</code>
   */
  int getRowLimit();
}
