// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CSVImport.proto

package com.dbmapp.dbmapp.grpc;

public final class CSVImportServiceImpl {
  private CSVImportServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSVRowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CSVRow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Schema to import into
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    java.lang.String getSchemaName();
    /**
     * <pre>
     * Schema to import into
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSchemaNameBytes();

    /**
     * <pre>
     * Table to import into
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    java.lang.String getTableName();
    /**
     * <pre>
     * Table to import into
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <pre>
     * The actual values of the CSV row
     * </pre>
     *
     * <code>repeated string values = 3;</code>
     */
    java.util.List<java.lang.String>
        getValuesList();
    /**
     * <pre>
     * The actual values of the CSV row
     * </pre>
     *
     * <code>repeated string values = 3;</code>
     */
    int getValuesCount();
    /**
     * <pre>
     * The actual values of the CSV row
     * </pre>
     *
     * <code>repeated string values = 3;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <pre>
     * The actual values of the CSV row
     * </pre>
     *
     * <code>repeated string values = 3;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);
  }
  /**
   * <pre>
   * Message: CSVRow
   * -----------------------------------------------
   * Represents one row of CSV data sent to the server.
   * The data is modeled as repeated string to support dynamic headers.
   * </pre>
   *
   * Protobuf type {@code CSVRow}
   */
  public  static final class CSVRow extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CSVRow)
      CSVRowOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSVRow.newBuilder() to construct.
    private CSVRow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSVRow() {
      schemaName_ = "";
      tableName_ = "";
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSVRow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              schemaName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              values_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = values_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_CSVRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_CSVRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow.class, com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow.Builder.class);
    }

    private int bitField0_;
    public static final int SCHEMA_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object schemaName_;
    /**
     * <pre>
     * Schema to import into
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Schema to import into
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object tableName_;
    /**
     * <pre>
     * Table to import into
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Table to import into
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <pre>
     * The actual values of the CSV row
     * </pre>
     *
     * <code>repeated string values = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValuesList() {
      return values_;
    }
    /**
     * <pre>
     * The actual values of the CSV row
     * </pre>
     *
     * <code>repeated string values = 3;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <pre>
     * The actual values of the CSV row
     * </pre>
     *
     * <code>repeated string values = 3;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <pre>
     * The actual values of the CSV row
     * </pre>
     *
     * <code>repeated string values = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSchemaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schemaName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableName_);
      }
      for (int i = 0; i < values_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, values_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSchemaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schemaName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += computeStringSizeNoTag(values_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow other = (com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow) obj;

      boolean result = true;
      result = result && getSchemaName()
          .equals(other.getSchemaName());
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && getValuesList()
          .equals(other.getValuesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaName().hashCode();
      hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: CSVRow
     * -----------------------------------------------
     * Represents one row of CSV data sent to the server.
     * The data is modeled as repeated string to support dynamic headers.
     * </pre>
     *
     * Protobuf type {@code CSVRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CSVRow)
        com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_CSVRow_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_CSVRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow.class, com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schemaName_ = "";

        tableName_ = "";

        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_CSVRow_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow build() {
        com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow buildPartial() {
        com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow result = new com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.schemaName_ = schemaName_;
        result.tableName_ = tableName_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = values_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.values_ = values_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow other) {
        if (other == com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow.getDefaultInstance()) return this;
        if (!other.getSchemaName().isEmpty()) {
          schemaName_ = other.schemaName_;
          onChanged();
        }
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object schemaName_ = "";
      /**
       * <pre>
       * Schema to import into
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public java.lang.String getSchemaName() {
        java.lang.Object ref = schemaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schemaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Schema to import into
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaNameBytes() {
        java.lang.Object ref = schemaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Schema to import into
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schemaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Schema to import into
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder clearSchemaName() {
        
        schemaName_ = getDefaultInstance().getSchemaName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Schema to import into
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schemaName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tableName_ = "";
      /**
       * <pre>
       * Table to import into
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Table to import into
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Table to import into
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Table to import into
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Table to import into
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValuesList() {
        return values_.getUnmodifiableView();
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual values of the CSV row
       * </pre>
       *
       * <code>repeated string values = 3;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CSVRow)
    }

    // @@protoc_insertion_point(class_scope:CSVRow)
    private static final com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow();
    }

    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSVRow>
        PARSER = new com.google.protobuf.AbstractParser<CSVRow>() {
      @java.lang.Override
      public CSVRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSVRow(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSVRow> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSVRow> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.CSVRow getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfirmationMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfirmationMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * True if import was successful
     * </pre>
     *
     * <code>bool ok = 1;</code>
     */
    boolean getOk();

    /**
     * <pre>
     * Optional message for logging/debugging
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Optional message for logging/debugging
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Message: ConfirmationMessage
   * -----------------------------------------------
   * Confirms success or failure of the CSV import.
   * </pre>
   *
   * Protobuf type {@code ConfirmationMessage}
   */
  public  static final class ConfirmationMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfirmationMessage)
      ConfirmationMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfirmationMessage.newBuilder() to construct.
    private ConfirmationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfirmationMessage() {
      ok_ = false;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfirmationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ok_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_ConfirmationMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_ConfirmationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage.class, com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage.Builder.class);
    }

    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <pre>
     * True if import was successful
     * </pre>
     *
     * <code>bool ok = 1;</code>
     */
    public boolean getOk() {
      return ok_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Optional message for logging/debugging
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional message for logging/debugging
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ok_ != false) {
        output.writeBool(1, ok_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ok_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage other = (com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage) obj;

      boolean result = true;
      result = result && (getOk()
          == other.getOk());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOk());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: ConfirmationMessage
     * -----------------------------------------------
     * Confirms success or failure of the CSV import.
     * </pre>
     *
     * Protobuf type {@code ConfirmationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfirmationMessage)
        com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_ConfirmationMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_ConfirmationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage.class, com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ok_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.internal_static_ConfirmationMessage_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage build() {
        com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage buildPartial() {
        com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage result = new com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage(this);
        result.ok_ = ok_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage other) {
        if (other == com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage.getDefaultInstance()) return this;
        if (other.getOk() != false) {
          setOk(other.getOk());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean ok_ ;
      /**
       * <pre>
       * True if import was successful
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <pre>
       * True if import was successful
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public Builder setOk(boolean value) {
        
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * True if import was successful
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public Builder clearOk() {
        
        ok_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Optional message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfirmationMessage)
    }

    // @@protoc_insertion_point(class_scope:ConfirmationMessage)
    private static final com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage();
    }

    public static com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfirmationMessage>
        PARSER = new com.google.protobuf.AbstractParser<ConfirmationMessage>() {
      @java.lang.Override
      public ConfirmationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfirmationMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfirmationMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfirmationMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.CSVImportServiceImpl.ConfirmationMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CSVRow_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CSVRow_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfirmationMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfirmationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CSVImport.proto\"A\n\006CSVRow\022\023\n\013schema_na" +
      "me\030\001 \001(\t\022\022\n\ntable_name\030\002 \001(\t\022\016\n\006values\030\003" +
      " \003(\t\"2\n\023ConfirmationMessage\022\n\n\002ok\030\001 \001(\010\022" +
      "\017\n\007message\030\002 \001(\t29\n\tCSVImport\022,\n\tImportC" +
      "SV\022\007.CSVRow\032\024.ConfirmationMessage(\001B.\n\026c" +
      "om.dbmapp.dbmapp.grpcB\024CSVImportServiceI" +
      "mplb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CSVRow_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CSVRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CSVRow_descriptor,
        new java.lang.String[] { "SchemaName", "TableName", "Values", });
    internal_static_ConfirmationMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfirmationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfirmationMessage_descriptor,
        new java.lang.String[] { "Ok", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
