// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DatabaseManagement.proto

package com.dbmapp.dbmapp.grpc;

public final class DatabaseManagementServiceImpl {
  private DatabaseManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SchemaRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SchemaRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Name of the schema (database) to manage
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    java.lang.String getSchemaName();
    /**
     * <pre>
     * Name of the schema (database) to manage
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSchemaNameBytes();
  }
  /**
   * <pre>
   * Message: SchemaRequest
   * -----------------------------------------------
   * Used for creating or deleting a database schema.
   * </pre>
   *
   * Protobuf type {@code SchemaRequest}
   */
  public  static final class SchemaRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SchemaRequest)
      SchemaRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SchemaRequest.newBuilder() to construct.
    private SchemaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SchemaRequest() {
      schemaName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SchemaRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              schemaName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest.class, com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest.Builder.class);
    }

    public static final int SCHEMA_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object schemaName_;
    /**
     * <pre>
     * Name of the schema (database) to manage
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Name of the schema (database) to manage
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSchemaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schemaName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSchemaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schemaName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest other = (com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest) obj;

      boolean result = true;
      result = result && getSchemaName()
          .equals(other.getSchemaName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: SchemaRequest
     * -----------------------------------------------
     * Used for creating or deleting a database schema.
     * </pre>
     *
     * Protobuf type {@code SchemaRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SchemaRequest)
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest.class, com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schemaName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaRequest_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest build() {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest buildPartial() {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest result = new com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest(this);
        result.schemaName_ = schemaName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest other) {
        if (other == com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest.getDefaultInstance()) return this;
        if (!other.getSchemaName().isEmpty()) {
          schemaName_ = other.schemaName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object schemaName_ = "";
      /**
       * <pre>
       * Name of the schema (database) to manage
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public java.lang.String getSchemaName() {
        java.lang.Object ref = schemaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schemaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Name of the schema (database) to manage
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaNameBytes() {
        java.lang.Object ref = schemaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Name of the schema (database) to manage
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schemaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name of the schema (database) to manage
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder clearSchemaName() {
        
        schemaName_ = getDefaultInstance().getSchemaName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name of the schema (database) to manage
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schemaName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SchemaRequest)
    }

    // @@protoc_insertion_point(class_scope:SchemaRequest)
    private static final com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest();
    }

    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SchemaRequest>
        PARSER = new com.google.protobuf.AbstractParser<SchemaRequest>() {
      @java.lang.Override
      public SchemaRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SchemaRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SchemaRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SchemaRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SchemaResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SchemaResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Name of a single schema in the list
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    java.lang.String getSchemaName();
    /**
     * <pre>
     * Name of a single schema in the list
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSchemaNameBytes();
  }
  /**
   * <pre>
   * Message: SchemaResponse
   * -----------------------------------------------
   * Used to stream a list of existing schemas from the server.
   * </pre>
   *
   * Protobuf type {@code SchemaResponse}
   */
  public  static final class SchemaResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SchemaResponse)
      SchemaResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SchemaResponse.newBuilder() to construct.
    private SchemaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SchemaResponse() {
      schemaName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SchemaResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              schemaName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse.class, com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse.Builder.class);
    }

    public static final int SCHEMA_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object schemaName_;
    /**
     * <pre>
     * Name of a single schema in the list
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Name of a single schema in the list
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSchemaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schemaName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSchemaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schemaName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse other = (com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse) obj;

      boolean result = true;
      result = result && getSchemaName()
          .equals(other.getSchemaName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: SchemaResponse
     * -----------------------------------------------
     * Used to stream a list of existing schemas from the server.
     * </pre>
     *
     * Protobuf type {@code SchemaResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SchemaResponse)
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse.class, com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schemaName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_SchemaResponse_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse build() {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse buildPartial() {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse result = new com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse(this);
        result.schemaName_ = schemaName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse other) {
        if (other == com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse.getDefaultInstance()) return this;
        if (!other.getSchemaName().isEmpty()) {
          schemaName_ = other.schemaName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object schemaName_ = "";
      /**
       * <pre>
       * Name of a single schema in the list
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public java.lang.String getSchemaName() {
        java.lang.Object ref = schemaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schemaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Name of a single schema in the list
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaNameBytes() {
        java.lang.Object ref = schemaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Name of a single schema in the list
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schemaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name of a single schema in the list
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder clearSchemaName() {
        
        schemaName_ = getDefaultInstance().getSchemaName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name of a single schema in the list
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schemaName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SchemaResponse)
    }

    // @@protoc_insertion_point(class_scope:SchemaResponse)
    private static final com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse();
    }

    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SchemaResponse>
        PARSER = new com.google.protobuf.AbstractParser<SchemaResponse>() {
      @java.lang.Override
      public SchemaResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SchemaResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SchemaResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SchemaResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.SchemaResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfirmationMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfirmationMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * true if the operation succeeded, false otherwise
     * </pre>
     *
     * <code>bool ok = 1;</code>
     */
    boolean getOk();

    /**
     * <pre>
     * Descriptive result message for logging/debugging
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Descriptive result message for logging/debugging
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Message: ConfirmationMessage
   * -----------------------------------------------
   * Generic response message for confirming success or failure.
   * </pre>
   *
   * Protobuf type {@code ConfirmationMessage}
   */
  public  static final class ConfirmationMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfirmationMessage)
      ConfirmationMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfirmationMessage.newBuilder() to construct.
    private ConfirmationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfirmationMessage() {
      ok_ = false;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfirmationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ok_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_ConfirmationMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_ConfirmationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage.class, com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage.Builder.class);
    }

    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <pre>
     * true if the operation succeeded, false otherwise
     * </pre>
     *
     * <code>bool ok = 1;</code>
     */
    public boolean getOk() {
      return ok_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Descriptive result message for logging/debugging
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Descriptive result message for logging/debugging
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ok_ != false) {
        output.writeBool(1, ok_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ok_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage other = (com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage) obj;

      boolean result = true;
      result = result && (getOk()
          == other.getOk());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOk());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: ConfirmationMessage
     * -----------------------------------------------
     * Generic response message for confirming success or failure.
     * </pre>
     *
     * Protobuf type {@code ConfirmationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfirmationMessage)
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_ConfirmationMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_ConfirmationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage.class, com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ok_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.internal_static_ConfirmationMessage_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage build() {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage buildPartial() {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage result = new com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage(this);
        result.ok_ = ok_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage other) {
        if (other == com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage.getDefaultInstance()) return this;
        if (other.getOk() != false) {
          setOk(other.getOk());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean ok_ ;
      /**
       * <pre>
       * true if the operation succeeded, false otherwise
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <pre>
       * true if the operation succeeded, false otherwise
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public Builder setOk(boolean value) {
        
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * true if the operation succeeded, false otherwise
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public Builder clearOk() {
        
        ok_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Descriptive result message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Descriptive result message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Descriptive result message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Descriptive result message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Descriptive result message for logging/debugging
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfirmationMessage)
    }

    // @@protoc_insertion_point(class_scope:ConfirmationMessage)
    private static final com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage();
    }

    public static com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfirmationMessage>
        PARSER = new com.google.protobuf.AbstractParser<ConfirmationMessage>() {
      @java.lang.Override
      public ConfirmationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfirmationMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfirmationMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfirmationMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.DatabaseManagementServiceImpl.ConfirmationMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SchemaRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SchemaRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SchemaResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SchemaResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfirmationMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfirmationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030DatabaseManagement.proto\032\033google/proto" +
      "buf/empty.proto\"$\n\rSchemaRequest\022\023\n\013sche" +
      "ma_name\030\001 \001(\t\"%\n\016SchemaResponse\022\023\n\013schem" +
      "a_name\030\001 \001(\t\"2\n\023ConfirmationMessage\022\n\n\002o" +
      "k\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\272\001\n\022DatabaseMan" +
      "agement\0224\n\014CreateSchema\022\016.SchemaRequest\032" +
      "\024.ConfirmationMessage\0228\n\013ListSchemas\022\026.g" +
      "oogle.protobuf.Empty\032\017.SchemaResponse0\001\022" +
      "4\n\014DeleteSchema\022\016.SchemaRequest\032\024.Confir" +
      "mationMessageB7\n\026com.dbmapp.dbmapp.grpcB" +
      "\035DatabaseManagementServiceImplb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_SchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SchemaRequest_descriptor,
        new java.lang.String[] { "SchemaName", });
    internal_static_SchemaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SchemaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SchemaResponse_descriptor,
        new java.lang.String[] { "SchemaName", });
    internal_static_ConfirmationMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ConfirmationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfirmationMessage_descriptor,
        new java.lang.String[] { "Ok", "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
