// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableManagement.proto

package com.dbmapp.dbmapp.grpc;

public final class TableManagementServiceImpl {
  private TableManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TableRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TableRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The schema where the table
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    java.lang.String getSchemaName();
    /**
     * <pre>
     * The schema where the table
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSchemaNameBytes();

    /**
     * <pre>
     * The table to be created/dropped
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    java.lang.String getTableName();
    /**
     * <pre>
     * The table to be created/dropped
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();
  }
  /**
   * <pre>
   * Message: TableRequest
   * -----------------------------------------------
   * Used to refer to a specific table within a given schema.
   * </pre>
   *
   * Protobuf type {@code TableRequest}
   */
  public  static final class TableRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TableRequest)
      TableRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TableRequest.newBuilder() to construct.
    private TableRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TableRequest() {
      schemaName_ = "";
      tableName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TableRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              schemaName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest.class, com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest.Builder.class);
    }

    public static final int SCHEMA_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object schemaName_;
    /**
     * <pre>
     * The schema where the table
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The schema where the table
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object tableName_;
    /**
     * <pre>
     * The table to be created/dropped
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The table to be created/dropped
     * </pre>
     *
     * <code>string table_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSchemaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schemaName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSchemaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schemaName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest other = (com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest) obj;

      boolean result = true;
      result = result && getSchemaName()
          .equals(other.getSchemaName());
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaName().hashCode();
      hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: TableRequest
     * -----------------------------------------------
     * Used to refer to a specific table within a given schema.
     * </pre>
     *
     * Protobuf type {@code TableRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TableRequest)
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest.class, com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schemaName_ = "";

        tableName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableRequest_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest build() {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest buildPartial() {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest result = new com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest(this);
        result.schemaName_ = schemaName_;
        result.tableName_ = tableName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest other) {
        if (other == com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest.getDefaultInstance()) return this;
        if (!other.getSchemaName().isEmpty()) {
          schemaName_ = other.schemaName_;
          onChanged();
        }
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object schemaName_ = "";
      /**
       * <pre>
       * The schema where the table
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public java.lang.String getSchemaName() {
        java.lang.Object ref = schemaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schemaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The schema where the table
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaNameBytes() {
        java.lang.Object ref = schemaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The schema where the table
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schemaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The schema where the table
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder clearSchemaName() {
        
        schemaName_ = getDefaultInstance().getSchemaName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The schema where the table
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schemaName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tableName_ = "";
      /**
       * <pre>
       * The table to be created/dropped
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The table to be created/dropped
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The table to be created/dropped
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The table to be created/dropped
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The table to be created/dropped
       * </pre>
       *
       * <code>string table_name = 2;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TableRequest)
    }

    // @@protoc_insertion_point(class_scope:TableRequest)
    private static final com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest();
    }

    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TableRequest>
        PARSER = new com.google.protobuf.AbstractParser<TableRequest>() {
      @java.lang.Override
      public TableRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TableRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TableRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TableRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SchemaRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SchemaRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The name of the schema to scan for tables
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    java.lang.String getSchemaName();
    /**
     * <pre>
     * The name of the schema to scan for tables
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSchemaNameBytes();
  }
  /**
   * <pre>
   * Message: SchemaRequest
   * -----------------------------------------------
   * Reused here for listing tables in a schema.
   * </pre>
   *
   * Protobuf type {@code SchemaRequest}
   */
  public  static final class SchemaRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SchemaRequest)
      SchemaRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SchemaRequest.newBuilder() to construct.
    private SchemaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SchemaRequest() {
      schemaName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SchemaRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              schemaName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_SchemaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_SchemaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest.class, com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest.Builder.class);
    }

    public static final int SCHEMA_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object schemaName_;
    /**
     * <pre>
     * The name of the schema to scan for tables
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The name of the schema to scan for tables
     * </pre>
     *
     * <code>string schema_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSchemaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schemaName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSchemaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schemaName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest other = (com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest) obj;

      boolean result = true;
      result = result && getSchemaName()
          .equals(other.getSchemaName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: SchemaRequest
     * -----------------------------------------------
     * Reused here for listing tables in a schema.
     * </pre>
     *
     * Protobuf type {@code SchemaRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SchemaRequest)
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_SchemaRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_SchemaRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest.class, com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schemaName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_SchemaRequest_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest build() {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest buildPartial() {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest result = new com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest(this);
        result.schemaName_ = schemaName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest other) {
        if (other == com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest.getDefaultInstance()) return this;
        if (!other.getSchemaName().isEmpty()) {
          schemaName_ = other.schemaName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object schemaName_ = "";
      /**
       * <pre>
       * The name of the schema to scan for tables
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public java.lang.String getSchemaName() {
        java.lang.Object ref = schemaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schemaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The name of the schema to scan for tables
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaNameBytes() {
        java.lang.Object ref = schemaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The name of the schema to scan for tables
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schemaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the schema to scan for tables
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder clearSchemaName() {
        
        schemaName_ = getDefaultInstance().getSchemaName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the schema to scan for tables
       * </pre>
       *
       * <code>string schema_name = 1;</code>
       */
      public Builder setSchemaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schemaName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SchemaRequest)
    }

    // @@protoc_insertion_point(class_scope:SchemaRequest)
    private static final com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest();
    }

    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SchemaRequest>
        PARSER = new com.google.protobuf.AbstractParser<SchemaRequest>() {
      @java.lang.Override
      public SchemaRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SchemaRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SchemaRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SchemaRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.SchemaRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TableResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TableResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A single table name in the schema
     * </pre>
     *
     * <code>string table_name = 1;</code>
     */
    java.lang.String getTableName();
    /**
     * <pre>
     * A single table name in the schema
     * </pre>
     *
     * <code>string table_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();
  }
  /**
   * <pre>
   * Message: TableResponse
   * -----------------------------------------------
   * Used to return one table name at a time (streamed).
   * </pre>
   *
   * Protobuf type {@code TableResponse}
   */
  public  static final class TableResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TableResponse)
      TableResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TableResponse.newBuilder() to construct.
    private TableResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TableResponse() {
      tableName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TableResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse.class, com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse.Builder.class);
    }

    public static final int TABLE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object tableName_;
    /**
     * <pre>
     * A single table name in the schema
     * </pre>
     *
     * <code>string table_name = 1;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * A single table name in the schema
     * </pre>
     *
     * <code>string table_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse other = (com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse) obj;

      boolean result = true;
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: TableResponse
     * -----------------------------------------------
     * Used to return one table name at a time (streamed).
     * </pre>
     *
     * Protobuf type {@code TableResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TableResponse)
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse.class, com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tableName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_TableResponse_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse build() {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse buildPartial() {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse result = new com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse(this);
        result.tableName_ = tableName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse other) {
        if (other == com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse.getDefaultInstance()) return this;
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tableName_ = "";
      /**
       * <pre>
       * A single table name in the schema
       * </pre>
       *
       * <code>string table_name = 1;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A single table name in the schema
       * </pre>
       *
       * <code>string table_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A single table name in the schema
       * </pre>
       *
       * <code>string table_name = 1;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A single table name in the schema
       * </pre>
       *
       * <code>string table_name = 1;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A single table name in the schema
       * </pre>
       *
       * <code>string table_name = 1;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TableResponse)
    }

    // @@protoc_insertion_point(class_scope:TableResponse)
    private static final com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse();
    }

    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TableResponse>
        PARSER = new com.google.protobuf.AbstractParser<TableResponse>() {
      @java.lang.Override
      public TableResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TableResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TableResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TableResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.TableResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfirmationMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfirmationMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * True if the operation succeeded
     * </pre>
     *
     * <code>bool ok = 1;</code>
     */
    boolean getOk();

    /**
     * <pre>
     * Optional message (success or error description)
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Optional message (success or error description)
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Message: ConfirmationMessage
   * -----------------------------------------------
   * Used to confirm if the operation was successful.
   * </pre>
   *
   * Protobuf type {@code ConfirmationMessage}
   */
  public  static final class ConfirmationMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfirmationMessage)
      ConfirmationMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfirmationMessage.newBuilder() to construct.
    private ConfirmationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfirmationMessage() {
      ok_ = false;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfirmationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ok_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_ConfirmationMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_ConfirmationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage.class, com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage.Builder.class);
    }

    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <pre>
     * True if the operation succeeded
     * </pre>
     *
     * <code>bool ok = 1;</code>
     */
    public boolean getOk() {
      return ok_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Optional message (success or error description)
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional message (success or error description)
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ok_ != false) {
        output.writeBool(1, ok_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ok_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage)) {
        return super.equals(obj);
      }
      com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage other = (com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage) obj;

      boolean result = true;
      result = result && (getOk()
          == other.getOk());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOk());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message: ConfirmationMessage
     * -----------------------------------------------
     * Used to confirm if the operation was successful.
     * </pre>
     *
     * Protobuf type {@code ConfirmationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfirmationMessage)
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_ConfirmationMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_ConfirmationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage.class, com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage.Builder.class);
      }

      // Construct using com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ok_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.internal_static_ConfirmationMessage_descriptor;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage getDefaultInstanceForType() {
        return com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage build() {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage buildPartial() {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage result = new com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage(this);
        result.ok_ = ok_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage) {
          return mergeFrom((com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage other) {
        if (other == com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage.getDefaultInstance()) return this;
        if (other.getOk() != false) {
          setOk(other.getOk());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean ok_ ;
      /**
       * <pre>
       * True if the operation succeeded
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <pre>
       * True if the operation succeeded
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public Builder setOk(boolean value) {
        
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * True if the operation succeeded
       * </pre>
       *
       * <code>bool ok = 1;</code>
       */
      public Builder clearOk() {
        
        ok_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Optional message (success or error description)
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional message (success or error description)
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional message (success or error description)
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional message (success or error description)
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional message (success or error description)
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfirmationMessage)
    }

    // @@protoc_insertion_point(class_scope:ConfirmationMessage)
    private static final com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage();
    }

    public static com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfirmationMessage>
        PARSER = new com.google.protobuf.AbstractParser<ConfirmationMessage>() {
      @java.lang.Override
      public ConfirmationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfirmationMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfirmationMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfirmationMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dbmapp.dbmapp.grpc.TableManagementServiceImpl.ConfirmationMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TableRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TableRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SchemaRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SchemaRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TableResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TableResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfirmationMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfirmationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025TableManagement.proto\032\033google/protobuf" +
      "/empty.proto\"7\n\014TableRequest\022\023\n\013schema_n" +
      "ame\030\001 \001(\t\022\022\n\ntable_name\030\002 \001(\t\"$\n\rSchemaR" +
      "equest\022\023\n\013schema_name\030\001 \001(\t\"#\n\rTableResp" +
      "onse\022\022\n\ntable_name\030\001 \001(\t\"2\n\023Confirmation" +
      "Message\022\n\n\002ok\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\247\001\n" +
      "\017TableManagement\0222\n\013CreateTable\022\r.TableR" +
      "equest\032\024.ConfirmationMessage\0220\n\tDropTabl" +
      "e\022\r.TableRequest\032\024.ConfirmationMessage\022." +
      "\n\nListTables\022\016.SchemaRequest\032\016.TableResp" +
      "onse0\001B4\n\026com.dbmapp.dbmapp.grpcB\032TableM" +
      "anagementServiceImplb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_TableRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TableRequest_descriptor,
        new java.lang.String[] { "SchemaName", "TableName", });
    internal_static_SchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SchemaRequest_descriptor,
        new java.lang.String[] { "SchemaName", });
    internal_static_TableResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TableResponse_descriptor,
        new java.lang.String[] { "TableName", });
    internal_static_ConfirmationMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ConfirmationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfirmationMessage_descriptor,
        new java.lang.String[] { "Ok", "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
